# Generated by Django 5.2.7 on 2026-04-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
