# Generated by Django 5.2.7 on 2026-04-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_alter_waitlist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='phone_number',
            field=models.CharField(),
        ),
    ]
